spring:
  datasource:
    url: jdbc:h2:async:file:./camunda-h2-database;TRACE_LEVEL_FILE=0;DB_CLOSE_ON_EXIT=FALSE
camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    client:
      base-url: http://localhost:8090/engine-rest
logging:
  level:
    org.camunda.bpm.client: DEBUG
